version: '3.9'

services:
    # Service WebSocket (Socket.IO, WebSocket natif, etc.)
    websocket:
        build:
            context: .
            dockerfile: ./websocket/Dockerfile
            args:
                WEBSOCKET_TYPE: ${WEBSOCKET_TYPE}
                WEBSOCKET_VERSION: ${WEBSOCKET_VERSION}
        volumes:
            - ./websocket:/app
        ports:
            - '3001:3001' # Port WebSocket
        environment:
            WEBSOCKET_TYPE: ${WEBSOCKET_TYPE}
            DB_TYPE: ${DB_TYPE}
            DB_HOST: db
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - db
        networks:
            - dev-env

networks:
    dev-env:
        external: false
